### ISSUE TITLE
Release to bump base dep / support GHC 8.10?

### ISSUE THREAD

**Issue by TomMD** [marcelbuesing/sendgrid-v3#17] opened 2020-08-18 17:54 UTC
Could we get a release to support GHC 8.10?

**Comment by szg251** [comment] 2020-08-22 08:36
The [base library version](https://github.com/marcelbuesing/sendgrid-v3/blob/dev/sendgrid-v3.cabal#L31) looks good to me, I guess the problem is that the latest version on Hackage is still 0.1.2.0

**Comment by TomMD** [comment] 2020-08-22 17:38
Yep, that would be the issue

**Comment by marcelbuesing** [comment] 2020-08-25 07:47
The automated deploy when tagging seems to have failed with the following message. I'll try to look into this.
```
Installing deploy dependencies
dpl.2

Preparing deploy
dpl.3

Deploying application

dist-newstyle/cache/config already exists, no checkout

Could not restore untracked files from stash entry
```

**Comment by szg251** [comment] 2020-08-25 10:13
@marcelbuesing Great, thank you!

**Comment by domenkozar** [comment] 2020-12-14 22:03
:pray:

**Comment by pbrisbin** [comment] 2021-01-04 14:43
:wave: Sorry to bug you about this, but we're doing an audit of our dependencies and trying to move away from as many git dependencies as possible. As such, we'd really like to see the latest version of this package back on Hackage (and ideally Stackage). As I understand it, there's just a bit of broken automation in the way. I looked into fixing things via a PR, but it looks like a contributor may just need to run the steps in #16 to get things moving again. Have you seen that, @marcelbuesing ?

**Comment by marcelbuesing** [comment] 2021-01-05 12:05
Finally published it, https://hackage.haskell.org/package/sendgrid-v3-0.3.0.0
Does anyone know of a Github Action for publishing to hackage? I'm also willing to add more maintainers to avoid my slow response, so if anyone is willing to jump in, please let me know.

**Comment by pbrisbin** [comment] 2021-01-05 16:20
Awesome thank you!

> Does anyone know of a Github Action for publishing to hackage? I'm also willing to add more maintainers

I would be happy to help out here, since Freckle relies on this package. I don't know of an existing Action, but I could look around, or I'd be interested in creating one anyway. Would you want to move CI entirely to Actions (looks like this project uses Travis now), or just the release step?

**Comment by marcelbuesing** [comment] 2021-01-06 01:31
> Awesome thank you!
> 
> > Does anyone know of a Github Action for publishing to hackage? I'm also willing to add more maintainers
> 
> I would be happy to help out here, since Freckle relies on this package. I don't know of an existing Action, but I could look around, or I'd be interested in creating one anyway. Would you want to move CI entirely to Actions (looks like this project uses Travis now), or just the release step?

I think it would probably make sense to completely migrate it due to the new Travis restrictions, I also had a feeling there was some deeper problem with the Travis hackage upload (as far as I remember it used to work), but I'm open to also just migrating the release step.
Thanks! I send you an invite and added you and @donatello as maintainers to the hackage package.

**Comment by donatello** [comment] 2022-06-27 19:00
Closing this as done.

**Closed as completed by donatello** 2022-06-27 19:00 UTC
